services:
  db:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fisa
      MYSQL_USER: user01
      MYSQL_PASSWORD: user01
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql-init-files/:/docker-entrypoint-initdb.d
      - ./fisa_dump.sql:/docker-entrypoint-initdb.d/fisa_dump.sql
    networks:
      - spring-mysql-net
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100

  newmysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=newfisa
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=user01
    ports:
      - "3307:3306"  # 호스트와의 포트 매핑
    volumes:
      - ./new_mysql_data:/var/lib/mysql
      - ./mysql-init-files/:/docker-entrypoint-initdb.d
      - ./fisa_dump.sql:/docker-entrypoint-initdb.d/fisa_dump.sql

  app:
    container_name: springbootapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8088:8080" 
    environment:
      MYSQL_HOST: db  # DB 호스트 설정
    depends_on:
      db:
        condition: service_healthy
    networks:
      - spring-mysql-net

networks:
  spring-mysql-net:
    driver: bridge  # 네트워크 드라이버 정의
